Repository BrightCoders-Proyectos/tribo-mobile, pull requests merged in 2021-01, with the labels that each got.

#26 Feature/14 welcome screen guest UI
  tribomobile/App.js
  tribomobile/components/screens/welcome/WelcomeGuestScreen.js
  tribomobile/package-lock.json
  tribomobile/package.json
  tribomobile/screens/SplashScreen.js
  tribomobile/screensText/contentText.js
Labels: brightcoders approved, ready for review, ready to merge

#28 Main screen
  tribomobile/App.js
  tribomobile/android/app/src/main/AndroidManifest.xml
  tribomobile/android/build.gradle
  tribomobile/android/settings.gradle
  tribomobile/assets/bars-solid.svg
  tribomobile/assets/food.png
  tribomobile/assets/menuImage.png
  tribomobile/assets/store.png
  tribomobile/assets/user.png
  tribomobile/assets/user1.png
  tribomobile/components/IconNav.js
  tribomobile/components/MapStyle.js
  tribomobile/components/constant.js
  tribomobile/components/mainScreen.js
  tribomobile/package-lock.json
  tribomobile/package.json
Labels: ready for review

#45 Feature/36 title component
  package-lock.json
  tribomobile/components/Titles.js
  tribomobile/screens/OnBoardScreenCall.js
  tribomobile/screens/OnBoardScreenConect.js
  tribomobile/screens/OnBoardScreenReceive.js
  tribomobile/src/colorsFile.js
Labels: 1p, ready for review

#49 Feature/38 create button component
  tribomobile/App.js
  tribomobile/ExampleButtons.js
  tribomobile/components/CustomButton.js
  tribomobile/components/screens/welcome/WelcomeScreen.js
  tribomobile/package-lock.json
  tribomobile/package.json
Labels: 1p, ready for review

#47 Create TextInputCompoent and add corresponidng color styles
  tribomobile/components/TextInputs.js
  tribomobile/package-lock.json
  tribomobile/src/colors.js
Labels: ready for review

#46 Creation and design of checkboxs components
  tribomobile/App.js
  tribomobile/components/CheckBoxCustom.js
  tribomobile/components/RadioButtonCustom.js
  tribomobile/package-lock.json
  tribomobile/package.json
Labels: 1p

#52 Feature/43 pop up component
  tribomobile/App.js
  tribomobile/__tests__/App-test.js
  tribomobile/__tests__/__snapshots__/App-test.js.snap
  tribomobile/components/CustomButton.js
  tribomobile/components/modals/ModalDeleteStore.js
  tribomobile/src/TitlesText.js
Labels: ready for review
