Repository BrightCoders-Proyectos/tribo-mobile, pull requests merged in 2021-02, with the labels that each got.

#51 Feature/41 menu bar
  tribomobile/App.js
  tribomobile/android/app/BUCK
  tribomobile/android/app/build.gradle
  tribomobile/android/app/build_defs.bzl
  tribomobile/android/app/debug.keystore
  tribomobile/android/app/proguard-rules.pro
  tribomobile/android/app/src/debug/AndroidManifest.xml
  tribomobile/android/app/src/debug/java/com/tribomobile/ReactNativeFlipper.java
  tribomobile/android/app/src/main/AndroidManifest.xml
  tribomobile/android/app/src/main/java/com/tribomobile/MainActivity.java
  tribomobile/android/app/src/main/java/com/tribomobile/MainApplication.java
  tribomobile/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  tribomobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  tribomobile/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  tribomobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  tribomobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  tribomobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  tribomobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  tribomobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  tribomobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  tribomobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  tribomobile/android/app/src/main/res/values/strings.xml
  tribomobile/android/app/src/main/res/values/styles.xml
  tribomobile/android/build.gradle
  tribomobile/android/gradle.properties
  tribomobile/android/gradle/wrapper/gradle-wrapper.jar
  tribomobile/android/gradle/wrapper/gradle-wrapper.properties
  tribomobile/android/gradlew.bat
  tribomobile/android/settings.gradle
  tribomobile/assets/allicon.png
  tribomobile/assets/backicon.png
  tribomobile/assets/food.png
  tribomobile/assets/foodicon.png
  tribomobile/assets/marker_food.png
  tribomobile/assets/marker_service.png
  tribomobile/assets/marker_store.png
  tribomobile/assets/serviceicon.png
  tribomobile/assets/services.png
  tribomobile/assets/store.png
  tribomobile/assets/storeicon.png
  tribomobile/components/BtnHideShowMenu.js
  tribomobile/components/ClicableLink.js
  tribomobile/components/IconNav.js
  tribomobile/components/LogoTribo.js
  tribomobile/components/MapStyle.js
  tribomobile/components/MenuComponent.js
  tribomobile/components/SideBarOption.js
  tribomobile/components/mainScreen.js
  tribomobile/components/menuHide.js
  tribomobile/components/modals/LittlePinInfo.js
  tribomobile/components/modals/ModalDeleteStore.js
  tribomobile/package-lock.json
  tribomobile/package.json
  tribomobile/screens/SideNavScreen.js
  tribomobile/screensText/contentText.js
  tribomobile/src/colors.js
  tribomobile/src/colorsFile.js
  tribomobile/styles/SideBarStyle.js
  tribomobile/yarn.lock
Labels: ready for review

#59 Create ReadmeScreen Component for sideNav component
  tribomobile/assets/close-strong.png
  tribomobile/components/LogoTribo.js
  tribomobile/components/Titles.js
  tribomobile/screens/ReadmeScreens.js
  tribomobile/screensText/ContentText.js
  tribomobile/src/TitlesText.js
Labels: ready for review

#67 Feature/57 register market place
  tribomobile/App.js
  tribomobile/components/CheckBoxCustom.js
  tribomobile/components/LogoTribo.js
  tribomobile/components/Titles.js
  tribomobile/package-lock.json
  tribomobile/screens/RegisterMarket.js
  tribomobile/screens/RegistrationScreen.js
  tribomobile/screens/SideNavScreen.js
  tribomobile/screensText/ContentText.js
  tribomobile/src/TitlesText.js
  tribomobile/yarn.lock
Labels: 1p, 2p

#74 Feature/66 profile screens component implementation
  tribomobile/App.js
  tribomobile/components/CheckBoxCustom.js
  tribomobile/components/RadioButtonCustom.js
  tribomobile/components/TextInputs.js
  tribomobile/components/Titles.js
  tribomobile/components/modals/ModalDeleteStoreOrAccout.js
  tribomobile/data/ProfileData.js
  tribomobile/package-lock.json
  tribomobile/screens/ProfileEditScreen.js
  tribomobile/screens/ProfileScreen.js
  tribomobile/screens/ReadmeScreens.js
  tribomobile/screensText/ContentText.js
  tribomobile/src/TitlesText.js
  tribomobile/yarn.lock
Labels: ready for review

#75 Feature/70 pin functionality
  tribomobile/App.js
  tribomobile/assets/card.png
  tribomobile/assets/cash.png
  tribomobile/assets/deliveryicon.png
  tribomobile/assets/newclose.png
  tribomobile/assets/pickupproduct.png
  tribomobile/components/BtnHideShowMenu.js
  tribomobile/components/IconNav.js
  tribomobile/components/MainScreen.js
  tribomobile/components/MenuComponent.js
  tribomobile/components/modals/LittlePinInfo.js
  tribomobile/components/modals/ModalInfoStore.js
  tribomobile/components/modals/ModalNotFound.js
  tribomobile/screensText/ContentText.js
  tribomobile/src/Colors.js
  tribomobile/src/TitlesText.js
Labels: 1p

#78 Feature/76 api consumption
  tribomobile/components/MainScreen.js
  tribomobile/components/modals/ModalInfoStore.js
Labels: 1p, ready for review

#77 Feature/60 sign up screen
  tribomobile/App.js
  tribomobile/components/screens/welcome/SignUpScreen.js
Labels: ready to merge
